import fs from "node:fs";
import path from "node:path";
import { scaffold } from "../src/scaffold.js";

const targetDir = path.resolve(process.cwd(), ".express-api");

fs.rmSync(targetDir, { recursive: true, force: true });
fs.mkdirSync(targetDir, { recursive: true });

await scaffold(targetDir, {
    projectConfig: {
        name: "express-api-test",
        version: "0.1.0",
        description: "Scaffolded test project generated by setup-express-api.",
        author: "",
        license: "MIT"
    }
});

console.log(`Scaffolded test project in ${targetDir}`);
